### ISSUE TITLE
[기술조사][Node.js] ssh 모듈 조사/사용해서 원격서버에 실행중인 프로세스 목록 얻어오는 테스트 코드 작성

### ISSUE THREAD

**Issue by norux** [norux/app-manager#2]
## Node.js ssh 모듈 조사/사용해서 원격서버에 실행중인 프로세스 목록 얻어오는 테스트 코드 작성

**Comment by norux** [comment]
예전에 조사할때 [ssh2](https://github.com/mscdex/ssh2) 이 모듈이 제일 좋아보이긴 했음

**Comment by hyoj** [comment]
@norux https://github.com/hyoj/app-manager/blob/master/test/ssh2-test.js

**Comment by norux** [comment]
research 폴더에 #2 폴더를 만들어서 커밋해주고, research/README.md의 open에 있는 이슈를 close로 옮기면서 #2 링크 달아주세용 :)

**Comment by hyoj** [comment]
이슈 종료합니다. ^ ^;
> [#2](https://github.com/norux/app-manager/tree/master/research/2)
